 
parameters:
  username:
    name: username
    description: Username to use for login.
    in: body
    required: true
    type: string
  password:
    name: password
    description: password to use for login.
    in: body
    required: true
    type: string
  description:
    name: description
    description: description of the class
    in: body
    required: true
    type: string
  teacherId:
    name: teacherId
    description: ID of the teacher
    in: session
    required: true
    type: integer
  classId:
    name: classId
    description: ID of the class
    in: params
    required: true
    type: integer

tags:
  - name: Login
    description: Login management
